CREATE TABLE IF NOT EXISTS `users` (
    `id` INT(10) AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(191),
    `password` VARCHAR(191),
    `role` VARCHAR(10) DEFAULT NULL,
    `status` TINYINT(1) DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB COMMENT 'list of users';