module.exports = [
    "action and adventure", 
    "anthology", 
    "classic", 
    "comic and graphic novel", 
    "crime and detective", 
    "drama", 
    "fable", 
    "fairy tale", 
    "fan-fiction", 
    "fantasy", 
    "historical fiction", 
    "horror", 
    "humor", 
    "legend", 
    "magical realism", 
    "mystery", 
    "mythology", 
    "realistic fiction", 
    "romance", 
    "satire", 
    "science fiction (sci-fi)", 
    "short story", 
    "suspense/thriller", 
    "biography/autobiography", 
    "essay", 
    "memoir", 
    "narrative nonfiction", 
    "periodicals", 
    "reference books", 
    "self-help book", 
    "speech", 
    "textbook", 
    "poetry"
];